### ISSUE TITLE
solidworks export gltf

### ISSUE THREAD

**Issue by sui0312feng** [weianweigan/SolidWorksLookup#4]
When exporting a SolidWorks model to GLTF format, how do you export the material textures within it?

**Comment by weianweigan** [comment]
@sui0312feng  This repos is lookup tool. There is nothing abot gltf. Are you add an issue to [DuSwTogltf](https://github.com/weianweigan/DuSwToglTF)?

---

May be you need this? [**How to export glb files?**](https://blog.dududu.space/archives/can-solidworks-export-glb-files)
